---
version: '3.4'

networks:
  expressed-realms-network:
    driver: bridge

services:
  myapp:
    image: node:21.6.1
    container_name: expressed-realms-vue-app
    working_dir: /app
    ports:
      - '5173:5173'
    volumes:
      - ./expressedrealms.client/:/app
      - /app/node_modules
      - ${USERPROFILE}/.aspnet/https:/https
    command: sh -c "npm run dev -- --host 0.0.0.0"
    networks:
      - expressed-realms-network
    depends_on:
      webapi:
        condition: service_started

  webapi:
    container_name: expressed-realms-web-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_HTTPS_PORTS=5001
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
      - ConnectionStrings__DefaultConnection=Host=expressed-realms-db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - SENDGRID_HOST=http://expressed-realms-sendgrid-mock:3000
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - FRONT_END_BASE_URL=https://localhost:5173
      - FROM_EMAIL=${FROM_EMAIL}
    ports:
      - '5000:5000'
      - '5001:5001'
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https:ro
    networks:
      - expressed-realms-network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: expressed-realms-db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - expressed-realms-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d expressedRealms"]
      interval: 2s
      timeout: 5s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:8.1
    container_name: expressed-realms-db-admin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgAdmin_data:/var/lib/pgadmin
    networks:
      - expressed-realms-network
    depends_on:
      postgres:
        condition: service_started

  sendgrid:
    container_name: expressed-realms-sendgrid-mock
    image: ghashange/sendgrid-mock:1.8.4
    ports:
      - '7000:3000'
    environment:
      - API_KEY=${SENDGRID_API_KEY}
    networks:
      - expressed-realms-network

volumes:
  ignore:
  db_data:
  pgAdmin_data:
