---

name: Build and Deploy Front End

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: false

on:
  push:
    branches: [main]
    paths:
      - 'client/**'
  pull_request:
    branches: [main]
    paths:
      - 'client/**'

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      statuses: write
    steps:
      # Git Checkout
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # If you use VALIDATE_ALL_CODEBASE = true, you can remove this line to improve performances

      # MegaLinter
      - name: MegaLinter
        id: ml
        # You can override MegaLinter flavor used to have faster performances
        # More info at https://megalinter.io/flavors/
        uses: oxsecurity/megalinter/flavors/javascript@v8.5.0
        env:
          # All available variables are described in documentation
          # https://megalinter.io/configuration/
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} # Validates all source when push on main, else just the git diff with main. Override with true if you always want to lint all sources
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # ADD YOUR CUSTOM ENV VARIABLES HERE OR DEFINE THEM IN A FILE .mega-linter.yml AT THE ROOT OF YOUR REPOSITORY
          # DISABLE: COPYPASTE,SPELL # Uncomment to disable copy-paste and spell checks

      # Upload MegaLinter artifacts
      - name: Archive production artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            mega-linter.log

      - name: Upload MegaLinter scan results to GitHub Security tab
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'megalinter-reports/megalinter-report.sarif'

  # Cypress Test Job
#  cypress-run-chrome:
#    name: Cypress Test (Chrome)
#    runs-on: ubuntu-22.04
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v4

#      - name: Build Docker Image
#        run: docker build ./client

#      - name: Run Cypress Tests
#        uses: cypress-io/github-action@v6
#        with:
#          component: true
#          browser: chrome
#          working-directory: client
#          record: true
#          tag: pr-component-chrome

  # Build and Push Docker Image
  push_to_docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # Pinned SHA for security
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7 # Pinned SHA for security
        with:
          images: noremacskich/expressedrealms-frontend

      - name: Build and Push Docker Image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # Pinned SHA for security
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: noremacskich/expressedrealms-frontend:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

  # Deployment Job
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-22.04
    needs: [push_to_docker]
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Azure Login
        uses: azure/login@v1.4.7
        with:
          client-id: ${{ secrets.EXPRESSEDREALMSFRONTEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.EXPRESSEDREALMSFRONTEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.EXPRESSEDREALMSFRONTEND_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Container to Azure
        uses: azure/container-apps-deploy-action@v2
        with:
          registryUrl: ${{ vars.EXPRESSEDREALMSFRONTEND_REGISTRY_URL }}
          registryUsername: ${{ secrets.EXPRESSEDREALMSFRONTEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.EXPRESSEDREALMSFRONTEND_REGISTRY_PASSWORD }}
          imageToDeploy: ${{ vars.EXPRESSEDREALMSFRONTEND_REGISTRY_URL }}/noremacskich/expressedrealms-frontend:${{ github.sha }}
          containerAppName: ca-expressedrealms-frontend
          resourceGroup: RG_ExpressedRealms
